package com.example.ai.service.generator;

import com.example.ai.config.AiProperties;
import com.example.ai.dto.GenerateRequest;
import com.example.ai.dto.GenerationResult;
import com.example.ai.service.client.AiClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * AI 서비스를 통해 eXbuilder6 레이아웃 XML(clx) 코드를 생성하는 생성기입니다.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class LayoutGenerator implements StageGenerator {

    private final AiProperties aiProperties;
    private final List<AiClient> aiClients;
    
    @Override
    public boolean supports(String stage) {
        return "layout".equalsIgnoreCase(stage);
    }

    @Override
    public void generate(GenerateRequest request, GenerationResult.GenerationResultBuilder builder) {
        String provider = aiProperties.getProvider();
        log.info("Generating Layout XML using provider: {}", provider);
        
        AiClient client = aiClients.stream()
                .filter(c -> c.supports(provider))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("Unsupported AI provider: " + provider));

        String clxCode = client.generateContent(request);
        
        builder.clxCode(clxCode)
                .previewMock("<div style=\"padding:20px; background:white; color:black;\"><h3>eXbuilder6 Preview Mock</h3><p>Generated by AI</p></div>")
                .explanation("Layout XML structure generated via " + provider);
    }
}
