package com.example.ai.service.generator;

import com.example.ai.config.AiProperties;
import com.example.ai.dto.GenerateRequest;
import com.example.ai.dto.GenerationResult;
import com.example.ai.service.client.AiClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * AI 서비스를 통해 eXbuilder6 레이아웃 XML(clx) 코드를 생성하는 생성기입니다.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class LayoutGenerator implements StageGenerator {

    private final AiProperties aiProperties;
    private final List<AiClient> aiClients;
    private final AiResponseParser aiResponseParser;
    
    @Override
    public boolean supports(String stage) {
        return "layout".equalsIgnoreCase(stage);
    }

    @Override
    public void generate(GenerateRequest request, GenerationResult.GenerationResultBuilder builder) {
        String provider = aiProperties.getProvider();
        log.info("Generating Layout XML using provider: {}", provider);
        
        AiClient client = aiClients.stream()
                .filter(c -> c.supports(provider))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("Unsupported AI provider: " + provider));

        String content = client.generateContent(request);
        GenerationResult parsed = aiResponseParser.parse(content);

        if (parsed != null) {
            if (parsed.getClxCode() != null) builder.clxCode(parsed.getClxCode());
            if (parsed.getPreviewMock() != null) builder.previewMock(parsed.getPreviewMock());
            if (parsed.getExplanation() != null) builder.explanation(parsed.getExplanation());
            if (parsed.getLogs() != null) {
                parsed.getLogs().forEach(builder::log);
            }
        } else {
            log.info("Falling back to raw Layout XML Code: {}", content);
            builder.clxCode(content)
                    .previewMock("<div style=\"padding:20px; background:white; color:black;\"><h3>eXbuilder6 Preview Mock</h3><p>Generated by AI</p></div>")
                    .explanation("Layout XML structure generated via " + provider);
        }
    }
}
