server:
  port: 8080

spring:
  application:
    name: exbuilder6-ai-server

# AI 생성 엔진 상세 설정
ai:
  generation:
    # 사용할 AI 서비스 선택: gemini, ollama, vllm
    provider: ollama
    
    # 서비스별 상세 접속 정보
    providers:
      gemini:
        api-key: "AIzaSyByrLy3qQ8AcvlgGy4yeh3qXYRnjsaz_04"
        model: "gemini-2.0-flash"
      ollama:
        api-url: "http://localhost:11434"
        model: "glm-5:cloud"
      vllm:
        api-url: "http://your-vllm-host:8000"
        model: "your-model-name"

    active-stages:
      - sql
      - server
      - layout
      - script
    
    # MCP (Model Context Protocol) 설정
    mcp:
      enabled: true
      servers:
        - name: "dbhelper"
          url: "http://localhost:7070/sse"
          description : "테이블 스크립트 생성시 데이터베이스에 관한 정보를 제공합니다."
        # - name: "filesystem-tool"
        #   url: "http://localhost:8002"
        # - name: "maven-agent"
        #   url: "http://localhost:8003"
      # 단계별 사용할 MCP 서버 지정
      stage-servers:
        sql: ["dbhelper"]
        # server: ["filesystem-tool", "maven-agent"]
        # layout: ["filesystem-tool"]
        # script: ["filesystem-tool"]
    
    server:
      base-package: com.example.resource.complex.item
      package-mapping:
        controller: controller
        service: service
        model: model
