package com.example.ai.service;

import com.example.ai.config.AiProperties;
import com.example.ai.dto.GenerateRequest;
import com.example.ai.dto.GenerationResult;
import com.example.ai.service.generator.SqlGenerator;
import com.example.ai.service.client.GeminiAiClient;
import com.example.ai.service.client.OllamaAiClient;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@Slf4j
@ExtendWith(MockitoExtension.class)
public class GenerationServiceTest {

    private GenerationService generationService;
    
    @Mock
    private AiProperties aiProperties;
    
    @Mock
    private GeminiAiClient geminiClient;
    
    @Mock
    private OllamaAiClient ollamaClient;

    @BeforeEach
    void setUp() {
        lenient().when(aiProperties.getActiveStages()).thenReturn(Arrays.asList("sql", "server"));
        SqlGenerator sqlGenerator = new SqlGenerator(aiProperties, Arrays.asList(geminiClient, ollamaClient));
        generationService = new GenerationService(Arrays.asList(sqlGenerator), aiProperties);
    }

    @Test
    void testGeminiGeneration() {
        when(aiProperties.getProvider()).thenReturn("gemini");
        when(geminiClient.supports("gemini")).thenReturn(true);
        when(geminiClient.generateContent(any(GenerateRequest.class))).thenReturn("SELECT * FROM GEMINI;");

        GenerateRequest request = new GenerateRequest();
        request.setStage("sql");
        request.setPrompt("사용자 이력 조회 sql 생성");

        GenerationResult result = generationService.processStage(request);

        assertNotNull(result);
        verify(geminiClient).generateContent(any(GenerateRequest.class));
    }

    @Test
    void testOllamaGeneration() {
        // Given
        String prompt = "사용자 이력 조회 sql 생성";
        String mockResponse = "-- Generated by Ollama\nSELECT * FROM TB_USER_HISTORY WHERE USER_ID = 'test';";
        
        when(aiProperties.getProvider()).thenReturn("ollama");
        when(ollamaClient.supports("ollama")).thenReturn(true);
        when(ollamaClient.generateContent(any(GenerateRequest.class))).thenReturn(mockResponse);

        GenerateRequest request = new GenerateRequest();
        request.setStage("sql");
        request.setPrompt(prompt);

        // When
        log.info(">>> Testing Ollama with prompt: {}", prompt);
        GenerationResult result = generationService.processStage(request);

        // Then
        System.out.println("\n==================================================");
        System.out.println("[Ollama Unit Test Result]");
        System.out.println("Prompt: " + prompt);
        System.out.println("Generated SQL: \n" + result.getSqlCode());
        System.out.println("==================================================\n");

        assertNotNull(result);
        assertEquals(mockResponse, result.getSqlCode());
        verify(ollamaClient).generateContent(any(GenerateRequest.class));
    }
}
